dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.2.0
  - smartcontractkit/chainlink-brownie-contracts@0.6.1
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.2.0"
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.6.1"
dotenv: .env
networks:
  development:
    verify: False
  ganache:
    verify: False
  sepolia:
    verify: True
    eth_usd_price_feed: "0x694AA1769357215DE4FAC081bf1f309aDC325306"
  goerli:
    verify: True
    eth_usd_price_feed: "0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e"
  linea:
    verify: True
  taiko:
    verify: True
  scroll:
    verify: True
wallets:
  from_key: ${PRIVATE_KEY}
